#!/usr/bin/env python3
"""tube-autopilot SETUP WIZARD - connect your 4 YouTube channels in one sitting.

Runs on plain Python (NO pip installs needed). Start it by double-clicking
START-HERE.bat (Windows) or START-HERE.command (Mac), or run:

    python tools/setup_wizard.py                 # guide through all 4 channels
    python tools/setup_wizard.py --verify        # re-check saved connections
    python tools/setup_wizard.py --redo money    # redo one channel only

What it does for each channel (mindset / facts / tech / money):
  1. asks for the OAuth client JSON you downloaded from that channel's
     Google Cloud project (type the file path, or paste the JSON content)
  2. opens your browser -> you sign in with THAT channel's Gmail -> Allow
  3. catches the redirect and exchanges the code for a refresh token
  4. instantly verifies the connection by reading your live YouTube
     channel name + subscriber count
  5. saves everything to factory.env (your private keyring file -
     NEVER upload it anywhere)

When all 4 are green it prints the FACTORY_ENV blob - ONE block you paste
into GitHub as a single repository secret. Optionally paste the same blob
back to your assistant in chat for a pre-flight check before GitHub.

Full click-by-click instructions: SETUP.md (same folder).
"""
from __future__ import print_function

import argparse
import http.server
import json
import sys
import threading
import urllib.error
import urllib.parse
import urllib.request
import webbrowser
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ENV_FILE = ROOT / "factory.env"

AUTH_URL = "https://accounts.google.com/o/oauth2/v2/auth"
TOKEN_URL = "https://oauth2.googleapis.com/token"
WHOAMI_URL = ("https://www.googleapis.com/youtube/v3/channels"
              "?part=snippet,statistics&mine=true")
SCOPES = ["https://www.googleapis.com/auth/youtube.upload",
          "https://www.googleapis.com/auth/youtube.readonly"]

# (id, youtube channel name, suggested GCP project name, gmail slot)
CHANNELS = [
    ("mindset", "Zenith Mindset", "tube-zenith-mindset", "1"),
    ("facts",   "Fact Vault",     "tube-fact-vault",     "2"),
    ("tech",    "AI Chronicle",   "tube-ai-chronicle",   "3"),
    ("money",   "Wealth Signals", "tube-wealth-signals", "4"),
]

ENV_KEYS = ["YT_CLIENT_ID_{CH}", "YT_CLIENT_SECRET_{CH}", "YT_REFRESH_TOKEN_{CH}"]

# Optional private mapping: channel id -> that channel's Gmail address.
# If your download was personalized, this file exists and the wizard shows
# the EXACT address at every step (it is gitignored - never uploaded).
GMAILS = {}
try:
    _gf = ROOT / "data" / "my-gmails.json"
    if _gf.exists():
        GMAILS = json.loads(_gf.read_text(encoding="utf-8"))
except Exception:
    GMAILS = {}


def gmail_label(ch_id, slot):
    """Exact address when known, otherwise the generic slot hint."""
    return GMAILS.get(ch_id) or ("Gmail #%s" % slot)


# ---------------------------------------------------------------- env file

def parse_env_text(text):
    data = {}
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, val = line.partition("=")
        if key.strip():
            data[key.strip()] = val.strip()
    return data


def load_env():
    if ENV_FILE.exists():
        try:
            return parse_env_text(ENV_FILE.read_text(encoding="utf-8"))
        except Exception:
            pass
    return {}


def save_env(data):
    lines = ["# tube-autopilot private keyring - NEVER upload this file anywhere.",
             "# Generated by tools/setup_wizard.py"]
    for key in sorted(data):
        lines.append("%s=%s" % (key, data[key]))
    ENV_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8")


def channel_connected(data, ch_id):
    ch = ch_id.upper()
    return all(data.get(k.format(CH=ch)) for k in ENV_KEYS)


# ------------------------------------------------------------- http helpers

def _post(url, params):
    body = urllib.parse.urlencode(params).encode("utf-8")
    req = urllib.request.Request(url, data=body, headers={
        "Content-Type": "application/x-www-form-urlencoded"})
    try:
        with urllib.request.urlopen(req, timeout=40) as resp:
            return json.loads(resp.read().decode("utf-8")), None
    except urllib.error.HTTPError as e:
        try:
            err = json.loads(e.read().decode("utf-8"))
        except Exception:
            err = {"error": str(e)}
        return None, err
    except Exception as e:  # network down etc.
        return None, {"error": str(e)}


def _get_json(url, access_token):
    req = urllib.request.Request(url, headers={
        "Authorization": "Bearer " + access_token})
    try:
        with urllib.request.urlopen(req, timeout=40) as resp:
            return json.loads(resp.read().decode("utf-8")), None
    except urllib.error.HTTPError as e:
        try:
            err = json.loads(e.read().decode("utf-8"))
        except Exception:
            err = {"error": str(e)}
        return None, err
    except Exception as e:
        return None, {"error": str(e)}


def exchange_code(cid, csec, code, redirect_uri):
    return _post(TOKEN_URL, {
        "code": code, "client_id": cid, "client_secret": csec,
        "redirect_uri": redirect_uri, "grant_type": "authorization_code"})


def refresh_access(cid, csec, refresh_token):
    return _post(TOKEN_URL, {
        "client_id": cid, "client_secret": csec,
        "refresh_token": refresh_token, "grant_type": "refresh_token"})


def whoami(access_token):
    """Return (channel_dict_or_None, error)."""
    data, err = _get_json(WHOAMI_URL, access_token)
    if err:
        return None, err
    items = data.get("items", [])
    return (items[0] if items else None), None


# ---------------------------------------------------------- oauth listener

def _start_catcher():
    """Bind a loopback HTTP server. Returns (server, result, done_event, port)."""
    result, done = {}, threading.Event()

    class Handler(http.server.BaseHTTPRequestHandler):
        def do_GET(self):
            qs = urllib.parse.parse_qs(urllib.parse.urlparse(self.path).query)
            if "code" in qs:
                result["code"] = qs["code"][0]
                page = (b"<html><body style='font-family:sans-serif;"
                        b"background:#0d1b2a;color:#fff;text-align:center;"
                        b"padding-top:14vh'><h2>&#10004; Connected!</h2>"
                        b"<p>You can close this tab and go back to the terminal.</p>"
                        b"</body></html>")
            else:
                result["error"] = qs.get("error", ["unknown_error"])[0]
                page = (b"<html><body style='font-family:sans-serif;"
                        b"background:#0d1b2a;color:#fff;text-align:center;"
                        b"padding-top:14vh'><h2>&#10006; Google returned an error"
                        b"</h2><p>Go back to the terminal.</p></body></html>")
            self.send_response(200)
            self.send_header("Content-Type", "text/html; charset=utf-8")
            self.send_header("Content-Length", str(len(page)))
            self.end_headers()
            self.wfile.write(page)
            done.set()

        def log_message(self, *args):
            pass

    for port in (8912, 8913, 8914, 8915):
        try:
            srv = http.server.HTTPServer(("127.0.0.1", port), Handler)
            threading.Thread(target=srv.serve_forever, daemon=True).start()
            return srv, result, done, port
        except OSError:
            continue
    return None, {}, threading.Event(), 0


def _auth_url(cid, redirect_uri):
    return AUTH_URL + "?" + urllib.parse.urlencode({
        "client_id": cid,
        "redirect_uri": redirect_uri,
        "response_type": "code",
        "scope": " ".join(SCOPES),
        "access_type": "offline",
        "prompt": "consent",
    })


# ------------------------------------------------------------- user input

def _parse_client_secret(text):
    try:
        data = json.loads(text)
    except Exception:
        return None
    installed = data.get("installed") or data.get("web") or {}
    cid = installed.get("client_id")
    csec = installed.get("client_secret")
    if cid and csec:
        return cid, csec
    return None


def ask_client_secret(ch_id):
    print("\n[1] Where is the OAuth client JSON for '%s'?" % ch_id)
    print("    (the file you downloaded from Google Cloud - its name usually")
    print("     looks like client_secret_xxxx.json)")
    while True:
        raw = input("    Type its path (or paste the whole JSON): ").strip().strip('"').strip("'")
        if not raw:
            print("    (enter 'q' to abort)")
            continue
        if raw.lower() == "q":
            return None
        text = None
        p = Path(raw)
        if p.exists():
            try:
                text = p.read_text(encoding="utf-8")
            except Exception:
                text = None
        if text is None and raw.startswith("{"):
            text = raw  # pasted JSON content
        if text is None:
            print("    -> could not find that file. Try again (path or paste JSON).")
            continue
        parsed = _parse_client_secret(text)
        if not parsed:
            print("    -> that file does not look like an OAuth client JSON.")
            print("       Download it again: Google Cloud -> Credentials -> your")
            print("       Desktop client -> Download JSON.")
            continue
        return parsed


# ------------------------------------------------------------- connect flow

def connect_channel(ch_id, name, project, gmail_slot, data):
    ch = ch_id.upper()
    print("\n" + "=" * 66)
    print("  CONNECTING: %s   (channel id: %s)" % (name, ch_id))
    print("  Use %s for this one.  GCP project: %s"
          % (gmail_label(ch_id, gmail_slot), project))
    print("=" * 66)

    pair = ask_client_secret(ch_id)
    if not pair:
        print("   skipped.")
        return False
    cid, csec = pair

    srv, result, done, port = _start_catcher()
    if not srv:
        print("   ERROR: could not open a local port (8912-8915).")
        print("   Close other terminals running this wizard and try again.")
        return False

    url = _auth_url(cid, "http://localhost:%d" % port)
    print("\n[2] Opening your browser now...")
    print("    On the Google screen:")
    print("      - sign in with %s (the one that owns '%s')"
          % (gmail_label(ch_id, gmail_slot), name))
    print("      - if you see 'Google hasn't verified this app':")
    print("        click Advanced -> Go to %s (unsafe) -> Continue" % project)
    print("      - click ALLOW on the permission page")
    try:
        webbrowser.open(url)
    except Exception:
        print("    Could not open a browser automatically. Open this URL by hand:\n")
        print("    " + url + "\n")

    print("[3] Waiting for you in the browser (up to 5 minutes)...")
    ok = done.wait(timeout=300)
    srv.shutdown()
    if not ok:
        print("   Timed out - no answer from the browser. Re-run this channel:")
        print("   python tools/setup_wizard.py --redo %s" % ch_id)
        return False
    if "error" in result:
        print("   Google returned an error: %s" % result["error"])
        print("   Most common cause: you picked the wrong Google account.")
        print("   Re-run: python tools/setup_wizard.py --redo %s" % ch_id)
        return False

    print("[4] Exchanging the code for a permanent refresh token...")
    tokens, err = exchange_code(cid, csec, result["code"],
                                "http://localhost:%d" % port)
    if err or not tokens.get("refresh_token"):
        msg = (err or {}).get("error_description") or (err or {}).get("error") or "?"
        print("   Token exchange failed: %s" % msg)
        print("   Re-run: python tools/setup_wizard.py --redo %s" % ch_id)
        return False
    refresh_token = tokens["refresh_token"]
    access = tokens.get("access_token")

    print("[5] Verifying against the live YouTube API...")
    info, verr = (None, {"error": "skip"})
    if access:
        info, verr = whoami(access)
    if info is None and verr and verr.get("error") != "skip":
        # access token may have expired instantly; refresh and retry once
        rtok, rerr = refresh_access(cid, csec, refresh_token)
        if rtok:
            info, verr = whoami(rtok.get("access_token", ""))

    data["YT_CLIENT_ID_%s" % ch] = cid
    data["YT_CLIENT_SECRET_%s" % ch] = csec
    data["YT_REFRESH_TOKEN_%s" % ch] = refresh_token
    save_env(data)

    if info:
        stats = info.get("statistics", {})
        print("\n   CONNECTED  ->  channel '%s'" % info.get("snippet", {}).get("title", "?"))
        print("                 %s subscribers | %s videos"
              % (stats.get("subscriberCount", "?"), stats.get("videoCount", "?")))
        print("   Saved to factory.env")
        return True
    if verr and verr.get("error") == "skip":
        print("   Saved to factory.env (could not auto-verify - check with --verify)")
        return True
    print("\n   Token saved, BUT this Google account has no YouTube channel yet!")
    print("   Fix (2 minutes): open youtube.com with %s,"
          % gmail_label(ch_id, gmail_slot))
    print("   click your profile picture -> 'Create a channel' -> name it EXACTLY:")
    print("     %s" % name)
    print("   Then run:  python tools/setup_wizard.py --verify")
    return True


# ------------------------------------------------------------------ verify

def verify_all():
    data = load_env()
    if not data:
        print("factory.env not found - nothing to verify yet.")
        return 1
    failures = 0
    print("\n" + "-" * 66)
    print("VERIFYING ALL CHANNEL CONNECTIONS")
    print("-" * 66)
    for ch_id, name, _project, slot in CHANNELS:
        ch = ch_id.upper()
        cid = data.get("YT_CLIENT_ID_%s" % ch)
        csec = data.get("YT_CLIENT_SECRET_%s" % ch)
        rt = data.get("YT_REFRESH_TOKEN_%s" % ch)
        if not (cid and csec and rt):
            print("  %-15s NOT CONNECTED YET (run the wizard without flags)" % name)
            failures += 1
            continue
        toks, err = refresh_access(cid, csec, rt)
        if not toks:
            print("  %-15s FAIL: token refresh error: %s"
                  % (name, (err or {}).get("error", "?")))
            failures += 1
            continue
        info, werr = whoami(toks.get("access_token", ""))
        if info:
            stats = info.get("statistics", {})
            print("  %-15s OK -> '%s'  (%s subs | %s videos)"
                  % (name, info.get("snippet", {}).get("title", "?"),
                     stats.get("subscriberCount", "0"),
                     stats.get("videoCount", "0")))
        elif werr:
            print("  %-15s FAIL: %s" % (name, (werr or {}).get("error", "?")))
            failures += 1
        else:
            print("  %-15s TOKEN OK, but no YouTube channel on this account yet"
                  " (create it: youtube.com -> Create a channel)" % name)
            failures += 1
    if data.get("GEMINI_API_KEY"):
        print("  Gemini API key: present (AI-written scripts enabled)")
    else:
        print("  Gemini API key: not set (offline content banks will be used - fine)")
    print("-" * 66)
    print("RESULT: %s" % ("ALL GREEN" if failures == 0 else
                          "%d problem(s) - see above" % failures))
    return 0 if failures == 0 else 1


# ------------------------------------------------------------------- final

def print_final():
    data = load_env()
    print("\n" + "=" * 66)
    print("  SETUP STATUS")
    print("=" * 66)
    for ch_id, name, _project, _slot in CHANNELS:
        state = "CONNECTED " if channel_connected(data, ch_id) else "NOT YET    "
        gm = GMAILS.get(ch_id)
        print("  [%s] %s%s" % (state, name, ("  (%s)" % gm) if gm else ""))
    if not data.get("GEMINI_API_KEY"):
        ans = input("\nOptional: paste a free Gemini API key for AI-written "
                    "scripts\n(aistudio.google.com/apikey) - or press Enter to "
                    "skip: ").strip()
        if ans:
            data["GEMINI_API_KEY"] = ans
            save_env(data)
            print("  Gemini key saved.")

    if all(channel_connected(data, ch_id) for ch_id, *_ in CHANNELS):
        print("\n" + "=" * 66)
        print("  ALL 4 CHANNELS CONNECTED - your factory keyring is ready")
        print("=" * 66)
        print("\nNEXT STEPS (5 minutes, see SETUP.md Step 4):\n")
        print("  1. GitHub -> New repository -> name: tube-autopilot -> Public")
        print("  2. Upload this whole folder (EXCEPT the file factory.env -")
        print("     that one stays private on your computer forever)")
        print("  3. Repo -> Settings -> Secrets and variables -> Actions ->")
        print("     New repository secret ->")
        print("        Name:  FACTORY_ENV")
        print("        Secret: paste the block between the CUT lines below")
        print("  4. Repo -> Settings -> Actions -> General -> Workflow")
        print("     permissions -> 'Read and write permissions' -> Save")
        print("  5. Repo -> Actions -> enable -> daily-mindset -> Run workflow")
        print("\n---------- CUT HERE ------------------------------------------")
        for key in sorted(data):
            print("%s=%s" % (key, data[key]))
        print("---------- CUT HERE ------------------------------------------")
        print("\nTreat that block like a password. Paste the same block back to")
        print("your assistant in chat first if you want a pre-flight check")
        print("before touching GitHub.")


# ---------------------------------------------------------------- selftest

def selftest():
    # 1. env round-trip
    d = {"YT_CLIENT_ID_MINDSET": "abc.apps.googleusercontent.com",
         "YT_REFRESH_TOKEN_MINDSET": "1//xyz"}
    assert parse_env_text("\n".join("%s=%s" % kv for kv in d.items())) == d
    # 2. client secret parsing
    sample = json.dumps({"installed": {"client_id": "CID", "client_secret": "SEC"}})
    assert _parse_client_secret(sample) == ("CID", "SEC")
    assert _parse_client_secret("not json") is None
    # 3. auth URL shape
    u = _auth_url("CID", "http://localhost:8912")
    q = urllib.parse.parse_qs(urllib.parse.urlparse(u).query)
    assert q["client_id"] == ["CID"]
    assert q["access_type"] == ["offline"]
    assert q["prompt"] == ["consent"]
    assert "youtube.upload" in q["scope"][0] and "youtube.readonly" in q["scope"][0]
    assert q["redirect_uri"] == ["http://localhost:8912"]
    # 4. redirect parsing (query component, as the handler extracts it)
    query = urllib.parse.urlparse("http://localhost:8912/?code=4/AbCd&scope=x").query
    assert "code" in urllib.parse.parse_qs(query)
    # 5. connected-check
    assert channel_connected({"YT_CLIENT_ID_X": "a", "YT_CLIENT_SECRET_X": "b",
                              "YT_REFRESH_TOKEN_X": "c"}, "x") is True
    assert channel_connected({}, "x") is False
    # 6. gmail label with and without the private mapping file
    saved = dict(GMAILS)
    GMAILS.clear()
    assert gmail_label("mindset", "1") == "Gmail #1"
    GMAILS.update({"mindset": "x@gmail.com"})
    assert gmail_label("mindset", "1") == "x@gmail.com"
    GMAILS.clear()
    GMAILS.update(saved)
    print("selftest OK - wizard internals verified")


# -------------------------------------------------------------------- main

def main():
    ap = argparse.ArgumentParser(description="tube-autopilot setup wizard")
    ap.add_argument("--verify", action="store_true", help="re-check saved connections")
    ap.add_argument("--redo", metavar="CHANNEL",
                    help="redo one channel: mindset | facts | tech | money")
    ap.add_argument("--selftest", action="store_true", help=argparse.SUPPRESS)
    args = ap.parse_args()

    if args.selftest:
        selftest()
        return 0
    if args.verify:
        return verify_all()

    print("=" * 66)
    print("  TUBE-AUTOPILOT SETUP WIZARD")
    print("  4 YouTube channels -> 1 factory.env keyring -> 1 GitHub secret")
    print("  (detailed screenshots-style help: SETUP.md next to this file)")
    print("=" * 66)

    data = load_env()
    if args.redo:
        ch = args.redo.lower()
        if ch not in [c[0] for c in CHANNELS]:
            print("unknown channel '%s' (use mindset|facts|tech|money)" % ch)
            return 1
        for k in ENV_KEYS:
            data.pop(k.format(CH=ch.upper()), None)
        save_env(data)

    for ch_id, name, project, slot in CHANNELS:
        if channel_connected(data, ch_id) and not args.redo:
            print("  [CONNECTED ] %s - skipping (use --redo %s to redo)"
                  % (name, ch_id))
            continue
        try:
            connect_channel(ch_id, name, project, slot, data)
        except KeyboardInterrupt:
            print("\n  (interrupted - progress is saved; re-run any time)")
            return 1

    print_final()
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except KeyboardInterrupt:
        print("\nbye - re-run any time, progress is saved.")
        sys.exit(1)
